const visemesMapping = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
  "C0n": "viseme_PP",
  "C0i": "viseme_I",
  "C0h": "viseme_TH",
  "C0ao": "viseme_O",
  "，": "viseme_PP", // 假设逗号使用与 "X" 相同的 viseme
  "C0w": "viseme_PP",
  "C0uo": "viseme_U",
  "C0zh": "viseme_TH",
  "C0en": "viseme_PP",
  "C0d": "viseme_AA",
  "C0e": "viseme_O",
  "C0m": "viseme_PP",
  "C0ei": "viseme_I",
  "C0y": "viseme_I",
  "C0iou": "viseme_U",
  "C0b": "viseme_kk",
  "C0an": "viseme_AA",
  "C0f": "viseme_U",
  "C0a": "viseme_AA",
  "C0j": "viseme_I",
  "C0iao": "viseme_I",
  "C0ai": "viseme_AA",
  "C0g": "viseme_FF",
  "C0zh": "viseme_TH",
  "C0ian": "viseme_I",
  "C0sh": "viseme_TH",
  "C0iii": "viseme_I",
  "C0q": "viseme_PP",
  "C0ing": "viseme_I",
  "。": "viseme_PP" // 假设句号使用与 "X" 相同的 viseme
};

export default visemesMapping;